export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const DETAILS_LOADING = 'DETAILS_LOADING';
export const GET_DATABASE_DETAILS = 'GET_DATABASE_DETAILS';
export const GET_LEARNER_DETAILS = 'GET_LEARNER_DETAILS';
export const GET_MENTOR_DETAILS = 'GET_MENTOR_DETAILS';

export const CONNECT_DATABASE_LOADING = 'CONNECT_DATABASE_LOADING';